//OLED settings
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27

//RGB
#define WS2812_DI_PIN GP28
#define RGBLIGHT_LED_COUNT 8
#define RGBLIGHT_MODE_RAINBOW_MOOD
#define RGBLIGHT_MODE_RGB_TEST
#define RGBLIGHT_MODE_TWINKLE
#define RGBLIGHT_LIMIT_VAL 100

//Macros
#define SENDSTRING_BELL	
#define BELL_SOUND
